#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class Application < Model

    attr_reader :name, :channel_ids, :bridge_ids, :endpoint_ids, :device_names, :events_allowed, :events_disallowed

    def events_allowed=(val)
      @events_allowed ||= val.map { |v| object.new(v) }
    end

    def events_disallowed=(val)
      @events_disallowed ||= val.map { |v| object.new(v) }
    end


  end
end
