#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class Channel < Model

    attr_reader :id, :protocol_id, :name, :state, :caller, :connected, :accountcode, :dialplan, :creationtime, :language, :channelvars, :caller_rdnis

    def caller=(val)
      @caller ||= CallerID.new(val)
    end

    def connected=(val)
      @connected ||= CallerID.new(val)
    end

    def dialplan=(val)
      @dialplan ||= DialplanCEP.new(val)
    end

    def creationtime=(val)
      @creationtime ||= Time.parse(val)
    end

    def channelvars=(val)
      @channelvars ||= object.new(val)
    end


  end
end
